AllCops:
  TargetRubyVersion: 2.4
Metrics/MethodLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/SpaceBeforeFirstArg:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
