(load "~/.emacs.d/conf/edit_with_emacs")
(setq ispell-program-name "/opt/homebrew/bin/aspell")
(defun regexp-to-case-fold (regex)
  (replace-regexp-in-string "[a-zA-Z]"
                            #'(lambda (str) (concat "[" (downcase str) (upcase str) "]"))
                            regex
                            nil nil nil))
(defun highlight-copyrights ()
  (interactive)
  (save-excursion
    (save-restriction
      (widen)
      (goto-char (point-min))
      (let ((case-fold-search t))
        (highlight-regexp (regexp-to-case-fold "copyright\\|license\\|notice\\|original") 'hi-pink)
        (highlight-regexp (regexp-to-case-fold "gnu\\|gpl") 'hi-aquamarine)
        (highlight-regexp (regexp-to-case-fold "author\\|copied\\|created\\|derived\\|developed\\|developped\\|modified") 'hi-green)
        (highlight-regexp "stackoverflow\\|github" 'hi-yellow)
        (highlight-regexp "https?://" 'hi-yellow)
        (highlight-lines-matching-regexp ":[0-9]+:diff -.*$" 'hi-green)
        (highlight-regexp "diff:[0-9]+:\\++" 'hi-green)
        (highlight-regexp "[0-9]:\\+? *//" 'hi-salmon nil)
        ))))
(defun occur-copyrights ()
  "occur copyrights-related words in this buffer"
  (interactive)
  (occur
   (concat
    (regexp-to-case-fold "copyright\\|license\\|notice\\|original\\|gnu\\|gpl") "\\|"
    (regexp-to-case-fold "author[^i]\\|copied\\|created\\|derived\\|developed\\|developped\\|modified") "\\|"
    "stackoverflow\\|github"
    )))
(define-key global-map "\C-ch" 'highlight-regexp)
(define-key global-map "\C-cH" 'highlight-lines-matching-regexp)
(defun my-copy-line-to-buffer (arg)
  (save-excursion
    (let* ((st (progn (forward-line 0) (point)))
           (ed (progn (forward-line 1) (point)))
           (line (buffer-substring-no-properties st ed))
           (pos (buffer-substring-no-properties st
                                                (progn
                                                  (goto-char st)
                                                  (re-search-forward ":[0-9]+:" ed t)
                                                  (point)))))
      (set-buffer (get-buffer-create arg))
      (goto-char (point-max))
      (insert line)
      (message "Added to %s: %s" arg pos)))
  (forward-line 1))
(defvar my-knowhow "*knowhow*")
(defvar my-spec "*spec*")
(defvar my-codecopy "*code copy*")
(defun my-copy-line-to-codecopy ()
  (interactive)
  (my-copy-line-to-buffer my-codecopy))
(defun my-copy-line-to-spec ()
  (interactive)
  (my-copy-line-to-buffer my-spec))
(defun my-copy-line-to-knowhow ()
  (interactive)
  (my-copy-line-to-buffer my-knowhow))
(defun my-grep-highlight ()
  (interactive)
  (highlight-copyrights)
  (view-mode 1))
(defun open-url-in-line ()
  (interactive)
  (let ((line (thing-at-point 'line t)))
    (when (string-match "\\(https?://[^ \t\n\r>)`\"']+\\)" line)
      (let ((url (match-string 1 line)))
        (when (string= (substring url -1 nil) ".")
          (setq url (substring url 0 -1)))
        (call-process "/usr/bin/open" nil nil nil url)))))
(defun my-add-grep-binding ()
  (define-key grep-mode-map "C" 'my-copy-line-to-codecopy)
  (define-key grep-mode-map "S" 'my-copy-line-to-spec)
  (define-key grep-mode-map "K" 'my-copy-line-to-knowhow)
  (define-key grep-mode-map "H" 'my-grep-highlight)
  (define-key grep-mode-map "R" 'highlight-regexp)
  (define-key grep-mode-map "U" 'open-url-in-line)
  (define-key grep-mode-map "\C-cc" #'(lambda () (interactive) (switch-to-buffer-other-window my-codecopy)))
  (define-key grep-mode-map "\C-cs" #'(lambda () (interactive) (switch-to-buffer-other-window my-spec)))
  (define-key grep-mode-map "\C-ck" #'(lambda () (interactive) (switch-to-buffer-other-window my-knowhow)))
  )
(add-hook 'grep-mode-hook 'my-add-grep-binding)
(defun my-view-mode-hook ()
  (define-key view-mode-map "C" nil)
  (define-key view-mode-map "c" nil)
  )
(add-hook 'view-mode-hook 'my-view-mode-hook)
(defun escape-for-json ()
  (interactive "*")
  (save-excursion
    (while (re-search-forward "[\\\"]" nil t)
      (forward-char -1)
      (insert "\\")
      (forward-char 1)))
  (while (re-search-forward "\n" nil t)
    (replace-match "\\\\n")))
(set-register ?h "/opt/homebrew/bin/rg --sort=path --no-heading -H -n -Tmd -g '!**/Tests/**' -g '!**/Documentation~/**' -g '!*.meta' -i 'https?://' | egrep -v 'xmlns|DOCTYPE|apache.org/|w3.org/|ietf.org/'")
(set-register ?C "/opt/homebrew/bin/rg --sort=path --no-heading -H -n -Tmd -g '!**/Tests/**' -g '!**/Documentation~/**' -g '!*.meta' -i 'copyright|license|author[^i]|copied|created|derived|developed|developped|modified|notice|original|gnu|gpl|stackoverflow|github' | egrep -v 'xmlns|DOCTYPE|apache.org/|w3.org/|ietf.org/'")
(set-register ?c "copyright|license|author[^i]|copied|created|derived|developed|developped|modified|notice|original|gnu|gpl|stackoverflow|github")
(set-register ?f " | filter_license license_filter.txt")
(set-register ?F " | filter_license LICENSE")
