(cond ((eq window-system 'w32)
       (setq default-frame-alist
	     (append (list '(foreground-color . "black")
			   '(background-color . "LemonChiffon")
			   '(background-color . "gray")
			   '(border-color . "black")
			   '(mouse-color . "white")
			   '(cursor-color . "black")
			   '(width . 120)
			   '(height . 60)
			   '(top . 120)
			   '(left . 580))
		     default-frame-alist))
       (setq w32-recognize-altgr nil)
       (setq default-file-name-coding-system 'cp932)
       ))
